[package]
name = "pendulum-lib"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["penproto", "pengui", "penproxy", "penfw", "pensim"]
default-members = [".", "pengui", "penproxy", "pensim"]
resolver = "2"

[lib]
name = "pendulum_lib"
path = "src/lib.rs"

[features]
default = ["std"]
std = ["dep:bevy_ecs", "dep:postcard", "dep:serialport", "serde/std"]

[dependencies]
bevy_ecs = { version = "0.15", optional = true }
penproto = { path = "penproto" }
postcard = { version = "1.1", features = ["alloc"], optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serialport = { version = "4.8", optional = true }
uom = { version = "0.38.0", default-features = false, features = [
    "autoconvert",
    "f64",
    "si",
    "serde",
] }
