[build]
target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]

[target.xtensa-esp32-none-elf]
linker = "ldproxy"
rustflags = [
    "-C",
    "link-arg=--ldproxy-linker=/Users/alkasm/.rustup/toolchains/esp/xtensa-esp-elf/esp-15.2.0_20250920/xtensa-esp-elf/bin/xtensa-esp32-elf-gcc",
    "-C",
    "link-arg=-Tlinkall.x",
]
