[package]
name = "penproto"
version = "0.1.0"
edition = "2024"

[lib]
name = "penproto"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }
uom = { version = "0.38.0", default-features = false, features = [
    "autoconvert",
    "f64",
    "si",
    "serde",
] }
