[package]
name = "penfw"
version = "0.1.0"
edition = "2024"
default-run = "penfw"

[target.'cfg(target_os = "linux")'.dependencies]
bevy_ecs = "0.15"
mpu6050 = "0.1"
pendulum-lib = { path = ".." }
linux-embedded-hal = "0.3"
uom = { version = "0.38.0", default-features = false, features = ["autoconvert", "f64", "si", "serde"] }

[target.xtensa-esp32-none-elf.dependencies]
esp-hal = { version = "1.0.0", features = ["esp32", "unstable"] }
esp-hal-smartled2 = "0.28.1"
smart-leds = "0.4"
